-- Source file: examples/sample_db2_ddl.sql
-- Extracted: 2024-01-01T00:00:00Z

CREATE TABLE APP.AUDIT_LOG (
  LOG_ID INTEGER NOT NULL,
  TABLE_NAME VARCHAR(128) NOT NULL,
  ACTION VARCHAR(10) NOT NULL,
  USER_ID INTEGER DEFAULT CURRENT_USER,
  LOG_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  LOG_TIME TIME NOT NULL DEFAULT CURRENT_TIME,
  LOG_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NOTES VARCHAR
);
