-- Source file: examples/sample_db2_ddl.sql
-- Extracted: 2025-10-20T00:00:00Z

CREATE TABLE APP.ACCOUNT (
  ACCOUNT_ID INTEGER NOT NULL,
  NAME VARCHAR(100) NOT NULL DEFAULT '',
  CRT_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  BAL NUMBER(18,2) DEFAULT 0,
  NOTES VARCHAR,
  CODE CHAR(3),
  IS_ACTIVE SMALLINT DEFAULT 1
);
ALTER TABLE APP.ACCOUNT ADD PRIMARY KEY (ACCOUNT_ID);
