-- Source file: examples/sample_db2_ddl.sql
-- Extracted: 2025-10-20T00:00:00Z

CREATE TABLE APP.USER_PROFILE (
  USER_ID INTEGER NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  FULL_NAME VARCHAR(100),
  DESCRIPTION VARCHAR(500),
  AVATAR BINARY,
  PREFERENCES VARIANT,
  STATUS CHAR(1) DEFAULT 'A'
);
ALTER TABLE APP.USER_PROFILE ADD PRIMARY KEY (USER_ID);
