-- Source file: examples/sample_db2_ddl.sql
-- Extracted: 2024-01-01T00:00:00Z

CREATE TABLE APP.TRANSACTION (
  TXN_ID BIGINT NOT NULL,
  ACCOUNT_ID INTEGER NOT NULL,
  AMOUNT NUMBER(10,2) NOT NULL,
  RATE FLOAT,
  FEE FLOAT,
  CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  CREATED_TIME TIME NOT NULL DEFAULT CURRENT_TIME,
  UPDATED_TS TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP
);
