-- Sample DB2 DDL file for testing the converter
-- This file demonstrates various DB2 features that need conversion

-- Table 1: Basic table with common data types
CREATE TABLE APP.ACCOUNT (
  ACCOUNT_ID INTEGER NOT NULL CONSTRAINT PK_ACC PRIMARY KEY,
  NAME VARCHAR(100) FOR SBCS DATA NOT NULL WITH DEFAULT '',
  CRT_TS TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  BAL DECIMAL(18,2) WITH DEFAULT 0,
  NOTES CLOB(1M),
  CODE CHAR(3) WITH DEFAULT,
  IS_ACTIVE SMALLINT WITH DEFAULT 1
);

-- Table 2: Table with various numeric types
CREATE TABLE APP.TRANSACTION (
  TXN_ID BIGINT NOT NULL,
  ACCOUNT_ID INTEGER NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL,
  RATE REAL,
  FEE DOUBLE,
  CREATED_DATE DATE NOT NULL WITH DEFAULT CURRENT DATE,
  CREATED_TIME TIME NOT NULL WITH DEFAULT CURRENT TIME,
  UPDATED_TS TIMESTAMP WITH TIME ZONE WITH DEFAULT CURRENT TIMESTAMP
);

-- Table 3: Table with string types and constraints
CREATE TABLE APP.USER_PROFILE (
  USER_ID INTEGER NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  FULL_NAME GRAPHIC(100),
  DESCRIPTION VARGRAPHIC(500),
  AVATAR BLOB(2M),
  PREFERENCES XML,
  STATUS CHAR(1) WITH DEFAULT 'A',
  CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);

-- Table 4: Table with complex defaults
CREATE TABLE APP.AUDIT_LOG (
  LOG_ID INTEGER NOT NULL,
  TABLE_NAME VARCHAR(128) NOT NULL,
  ACTION VARCHAR(10) NOT NULL,
  USER_ID INTEGER WITH DEFAULT USER,
  LOG_DATE DATE NOT NULL WITH DEFAULT CURRENT DATE,
  LOG_TIME TIME NOT NULL WITH DEFAULT CURRENT TIME,
  LOG_TS TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
  NOTES CLOB(10M)
);
